### ISSUE TITLE
[question]: How to use filter in createNotification?

### ISSUE THREAD

**Issue by YohaanYoon** [OneSignal/onesignal-node-api#21]
### How can we help?

I want to use `filter` in `createNotification`.

refs. https://documentation.onesignal.com/reference/create-notification#send-to-users-based-on-filters

But, `new OneSignal.Notification()` does not have `filter`. 
How to use it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabioselau077** [comment]
same question...

**Comment by kesheshyan** [comment]
Hey guys, thanks for your patience! 
Happy to inform that NPM package for our Node client library has been updated to the up to date version: 1.0.0-beta5. 
https://www.npmjs.com/package/@onesignal/node-onesignal

There was a bug in our OpenAPI schema that prevented users for setting up the *filters* property on the Notification model. Here is how you can use it now:
```js
const notification = new OneSignal.Notification();
notification.app_id = app.id;

notification.contents = {
  en: "Gig'em Ags"
}

// required for Huawei
notification.headings = {
  en: "Gig'em Ags"
}

// Find all the users that have not spent any amount in USD on IAP.
// https://documentation.onesignal.com/reference/create-notification#send-to-users-based-on-filters
notification.filters = [
    {
        field: 'amount_spent',
        relation: '=',
        value: "0"
    },
];

const notification = await client.createNotification(notification);
```
