### ISSUE TITLE
[question]: createConfiguration implementation

### ISSUE THREAD

**Issue by elhe26** [OneSignal/onesignal-node-api#24]
### How can we help?

This configuration is not correct:

```javascript
const configuration = OneSignal.createConfiguration({
    userKey: '<YOUR_USER_KEY_TOKEN>',
    appKey: '<YOUR_APP_KEY_TOKEN>',
});
```

This is what's working:

```javascript
    const configuration = OneSignal.createConfiguration({
        authMethods: {
            app_key: {
                tokenProvider: {
                    getToken() {
                        return appKey;
                    },
                }
            } as OneSignal.HttpBearerConfiguration,
            user_key: {
                tokenProvider: {
                    getToken() {
                        return userKey;
                    },
                }
            } as OneSignal.HttpBearerConfiguration,
        }
    });
```

Where can I find `userKey` and `appKey`? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elhe26** [comment]
Hey @kesheshyan , any updates?

**Comment by elhe26** [comment]
If anyone is having doubts, check this [link](https://onesignal.com/blog/send-push-notifications-with-the-onesignal-nodejs-client-sdk/).

**Comment by jdegger** [comment]
Why did you close this? What am I missing? I see the same results

**Comment by kesheshyan** [comment]
Hey guys, sorry for confusion. We simplified `createConfiguration` to accept only APP_KEY and USER_Key in the recent versions. Please let me know if this still an issue and feel free to reopen it.

**Comment by suathh** [comment]
It is still unclear how to get those keys. What is APP_KEY, and what is USER_KEY? What are those referring to in the OneSignal Dashboard? There is unclear documentation.

**Comment by suathh** [comment]
I only find relevant information in another repository. Hope this helps to someone 
![image](https://github.com/user-attachments/assets/d1c7d515-31f8-4491-bcda-d43f1ad4f256)

**Comment by suathh** [comment]
This is the working combination ! 

![image](https://github.com/user-attachments/assets/61191b9b-e946-4873-90b0-654d25f9afd7)

**Comment by sherwinski** [comment]
Hey @suathh,

Apologies for any confusion caused here. As you pointed out, the `userAuthKey` maps to either the legacy User Auth key or the (more current) Organization API key. We'll be looking at updating this field in the future to be more clear to users what it corresponds to.

<img width="660" alt="image" src="https://github.com/user-attachments/assets/e8536510-07ab-4fd5-9f63-64c8e89a33e8">

For anyone else who might run into issues with this, please have a look at our documentation [[1]](https://documentation.onesignal.com/docs/keys-and-ids#organization-api-key)[[2]](https://documentation.onesignal.com/docs/keys-and-ids#migrating-from-legacy-api-keys)
