### ISSUE TITLE
[Bug]: Incorrect documentation for updating player tags

### ISSUE THREAD

**Issue by PreludeAndFugue** [OneSignal/onesignal-node-api#25]
### What's on your mind?

- The documentation includes a warning for the Android SDK. Should this be here?
- There is no sample code for this function call.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Happy to inform that NPM package for our Node client library has been updated to the up to date version: 1.0.0-beta5. 
https://www.npmjs.com/package/@onesignal/node-onesignal
