### ISSUE TITLE
[question]: How to pass name to Notification

### ISSUE THREAD

**Issue by xXBlackBulletXx** [OneSignal/onesignal-node-api#27]
### How can we help?

I'm using Notification model and i'm trying to send a SMS notification but i can't set `name` property of notification, required for sms notification. Is that a bug? Or i'm missing something? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment]
Hello,
Thanks for your patience. This has been fixed but we have not yet pushed to NPM. You can point your dependency to this repository in the meantime. We will try to get it out asap.

Cheers

**Comment by kesheshyan** [comment]
Happy to inform that NPM package for our Node client library has been updated to the up to date version: 1.0.0-beta5. 
https://www.npmjs.com/package/@onesignal/node-onesignal

**Comment by kesheshyan** [comment]
Feel free to reopen this issue if the problem persist.
