### ISSUE TITLE
[question]: Getting module not found when using Typescript

### ISSUE THREAD

**Issue by aslampr07** [OneSignal/onesignal-node-api#44]
### How can we help?

I am getting the following error when trying to run my typescript project.

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/aslampr07/Desktop/NRIBrokers/nri-server/node_modules/@onesignal/node-onesignal/dist/index.js' imported from /home/aslampr07/Desktop/NRIBrokers/nri-server/dist/utils/notifications.js

Looking at the node_modules, the dist directory is not presented there. It should have present there when installing?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aslampr07** [comment]
Seems like the `npm run prepare` is not running

**Comment by kesheshyan** [comment]
Hey @aslampr07 , what version do you use? I should have fixed this problem with the 1.0.0-beta7 version. Please let me know if the problem still persists.

**Comment by aslampr07** [comment]
Thanks @kesheshyan,  I was using 1.0.0-beta5, update to 1.0.0-beta7 and it is working fine.
