### ISSUE TITLE
[question]: Notification email preheader attribute

### ISSUE THREAD

**Issue by luhart** [OneSignal/onesignal-node-api#47]
### How can we help?

Hello!

This might be a bug, but I can't figure out how to include email preheaders in notifications I create. I don't see it in the Notifications model - is this just not yet implemented?

For context, I'm using 1.0.0-beta8.

Thank you :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @luhart apologies for the long delay. I am not sure when `email_preheader` was added to the Notification object but it has been available for a while now. Closing this.
