### ISSUE TITLE
[Bug]: Unable to create a notification in Supabase Deno runtime

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/onesignal-node-api#54]
### What happened?

When I run this line of code in a Deno environment,`const res = await onesignal.createNotification(notification)`, I get the following error: `TypeError: (0 , Pa.default) is not a function`.

I tried running the same sample in a Node environment; it worked fine.

For reference, here's my code:

```ts
const OnesignalAppId = process.env["ONESINGAL_APP_ID"]!;
const configuration = OneSignal.createConfiguration({
  userKey: process.env["ONESINGAL_USER_KEY"]!,
  appKey: process.env["ONESINGAL_APP_KEY"]!,
});
const osClient = new OneSignal.DefaultApi(configuration);
export const sendNotif = async (message: string, segments: string[]) => {
  console.log("App ID", OnesignalAppId);
  try {
    const notification = new OneSignal.Notification();
    notification.app_id = OnesignalAppId;
    notification.contents = {
      en: message,
    };
    notification.included_segments = [...segments];

    const res = await osClient.createNotification(notification);
    console.info("CreateNotif Response", res);
  } catch (err) {
    console.error(err);
  }
};
```

### Steps to reproduce?

```Markdown
1. Create a supabase edge function
2. Implement a function to send a notification
3. Request the edge function 
4. Observe that no motivation is received and an error message is produced.
```

### What did you expect to happen?

I expected it to work and send my device a notification. 

### Relevant log output

```Shell
TypeError: (0 , Pa.default) is not a function
    at t.send (https://esm.sh/v113/@onesignal/node-onesignal@1.0.0-beta9/deno/node-onesignal.mjs:2:1725)
    at https://esm.sh/v113/@onesignal/node-onesignal@1.0.0-beta9/deno/node-onesignal.mjs:5:95902
    at https://esm.sh/v113/@onesignal/node-onesignal@1.0.0-beta9/deno/node-onesignal.mjs:2:1392
    at async Server.<anonymous> (file:///home/deno/functions/push-to-all-subs/index.ts:20:17)
    at async Server.#respond (https://deno.land/std@0.177.0/http/server.ts:299:18)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bmalumphy** [comment]
@iAmWillShepherd is there any potential workaround for this or is it perhaps in the ticket pipeline for a sprint in the near future?

**Comment by kpturner** [comment]
> @iAmWillShepherd The only workaround I'm aware of is to use Node

What does that mean?  If you are using this SDK you are, by default, using Node.  Can you explain further what you mean by this workaround suggestion?

**Comment by iAmWillShepherd** [comment]
@kpturner 

> What does that mean? If you are using this SDK you are, by default, using Node. 

This issue is about Deno. 

From the issue description 👇🏽  

> When I run this line of code in a Deno environment

This SDK can be used in a Deno runtime, so it's not correct that using this SDK means using Node by default. 

> Can you explain further what you mean by this workaround suggestion?

Yes, the workaround is to tell Vercel (via Next) that the function should be run under a Node runtime.
