### ISSUE TITLE
[question]: Critical Notifications not working

### ISSUE THREAD

**Issue by jeremywj** [OneSignal/onesignal-node-api#57]
### How can we help?

If I use the onesignal "Send message" GUI form on the website I can get a critical alert on my test phone just fine.  This tells me my app is fine.  However, through the API with this plugin I can't get critical notifications to work.  See code below.  The notification with the code below will come through if I turn DND off.  However, with DND I get nothing even though I should.

const notification = new OneSignal.Notification();
    notification.app_id = ONESIGNAL_APP_ID;
    notification.include_player_ids = [pushId];
    notification.include_player_ids = [pushId];
    notification.priority = 10;
    notification.ios_interruption_level = "critical";
    notification.mutable_content = true;
    notification.data = {
        type: "test"
    }
    notification.android_channel_id = getAudioTag(sound).android;

    notification.ios_sound = getAudioTag(sound).ios;
    notification.contents = {
        en: "Test Push Notification @ " + pageGetTime((Date.now() / 1000), users.getUserData(userId).timeFormat)
    };
    notification.headings = {
        "en": "Test"
    }

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremywj** [comment]
Heh, after spending a whole day trying to figure out what I was doing wrong, I figured it out minutes after posting this.

The API here simply does not support it.

dist/modals/Notification.d.ts & .../Notification.js need to have this option added.  Major oversight in my opinion and should be added asap.

**Comment by emawby** [comment]
Thank you for reporting this gap. It has been noted!

**Comment by nan-li** [comment]
Closing since OP has reported this issue in https://github.com/OneSignal/onesignal-node-api/issues/72
