### ISSUE TITLE
[Feature]: an endpoint to get all relevant devices using external user id

### ISSUE THREAD

**Issue by sshanzel** [OneSignal/onesignal-node-api#59]
### What's on your mind?

Provide an API to support the case mentioned in the subject. Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@sshanzel Hello thank you for the suggestion! To clarify are you looking to get all devices that use a particular external user id, or all devices that have any external user id?

**Comment by sshanzel** [comment]
Hi @emawby! We are wanting to fetch all the devices under the particular external user id.

**Comment by nan-li** [comment]
Hi @sshanzel apologies for the delay. Are you looking for an endpoint like the [View user](https://documentation.onesignal.com/reference/view-user) endpoint?

You can fetch a user by external ID and view the user's subscriptions, properties, and aliases.
