### ISSUE TITLE
[question]: iOS time-sensitive notifications

### ISSUE THREAD

**Issue by Gondolav** [OneSignal/onesignal-node-api#60]
### How can we help?

Hi, how do I send programmatically iOS time-sensitive notifications (the ones with "interruption-level" set to "time-sensitive")? I can't find a reference to those in the docs. I see it is possible with the [web UI](https://documentation.onesignal.com/docs/ios-focus-modes-and-interruption-levels).

Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremywj** [comment]
This currently does not support the ios_interruption_level flag.  I ran into the same problem and fixed it by creating my own repo with support.

https://github.com/jeremywj/onesignal-api

**Comment by nan-li** [comment]
https://github.com/OneSignal/onesignal-node-api/issues/72
