### ISSUE TITLE
[Bug]: Does not support ios_interruption_level

### ISSUE THREAD

**Issue by jeremywj** [OneSignal/onesignal-node-api#72]
### What happened?

Title says it all.

### Steps to reproduce?

```Markdown
1. Try to send ios_interruption_level in the api request
2. It wont be sent to onesignal with this API.
```

### What did you expect to happen?

ios_interruption_level should be acknowledged by this api.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @jeremywj thanks for reporting. We are working on another release and will include both `ios_relevance_score` and `ios_interruption_level`.

**Comment by jeremywj** [comment]
Thank you!

**Comment by nan-li** [comment]
Hi @jeremywj , thank you again for reporting and for your patience. 

We recently released an alpha version of our latest user model API: [Release 5.0.0-alpha-01](https://github.com/OneSignal/onesignal-node-api/releases/tag/5.0.0-alpha-01) that addresses this and other issues.

Please read the release description for how to get started, and we appreciate any early feedback on this release.

**Comment by hyped0001** [comment]
So this will only work on the new user model?

**Comment by jeremywj** [comment]
hyped0001, if you need to get this working I have it fixed in a fork for the old modal: https://github.com/jeremywj/onesignal-api

**Comment by jinliu9508** [comment]
Hi, we have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
