### ISSUE TITLE
[Bug]: createNofitication returning { id: '', errors: {} }

### ISSUE THREAD

**Issue by Gudaites** [OneSignal/onesignal-node-api#73]
### What happened?

I have some cases of sending push notifications where I cannot identify the errors and the createNotification function does not return any information about the error.

### Steps to reproduce?

```Markdown
version 2.0.1-beta2

I create the object with the OneSignalNotification type

and send with await this.oneSignalService.createNotification(notificationsBody);

when sent successfully it returns the right information but there is no error, I am just receiving errors: {}
```

### What did you expect to happen?

I hope that at least I can get back to the error that happened

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GizemSever** [comment]
I had the same problem, my example request was as follows

```
    const not = new OneSignal.Notification();
    not.app_id = this.appId;
    not.name = 'Test notification name ';
    not.headings = {

      'en': 'Test Notification title',
    };
    not.contents = {
      'en': 'Test Notification content',

    };
    not.target_channel = 'push';

    not.include_aliases = {
      'external_id': ['1', '2'],
    }

    const res = await this.client.createNotification(not);
```

I noticed that the external_id value in the include_aliases value was not included in the sent http request. If the body value you posted is similar, I fixed it and created a [pull request](https://github.com/OneSignal/onesignal-node-api/pull/74)

**Comment by nan-li** [comment]
Hi everyone, thank you for reporting and for your patience. 

We recently released an alpha version of our latest user model API: [Release 5.0.0-alpha-01](https://github.com/OneSignal/onesignal-node-api/releases/tag/5.0.0-alpha-01) that addresses this and other issues.

Please read the release description for how to get started, and we appreciate any early feedback on this release.

**Comment by jinliu9508** [comment]
Hi, we have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
