### ISSUE TITLE
[Bug]: Getting error 400 without any specific details

### ISSUE THREAD

**Issue by sjorobekov** [OneSignal/onesignal-node-api#75]
### What's on your mind?

How should I understand what should be changed in my request?

```
Error: HTTP-Code: 400
Message: Bad Request
Body: {"errors":[{}]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @sjorobekov, thank you for reporting. We are in the process of updating the error types. Can you share what request you were making that resulted in this failure?

**Comment by sjorobekov** [comment]
> Hi @sjorobekov, thank you for reporting. We are in the process of updating the error types. Can you share what request you were making that resulted in this failure?
Hi @nan-li. Thank you for your reply. I was experimenting with different data, and now it is working, and I don't remember what was the initial payload. So closing the issue

**Comment by nan-li** [comment]
@sjorobekov Ok! 
If you run into this again, please let us know, so we can work on a fix to make the errors more detailed.

**Comment by ansh** [comment]
@sjorobekov Can you share your working code? I am getting `400` error when I try the code from the docs

**Comment by nan-li** [comment]
Hi @sjorobekov,

Can you share the code you are running?

**Comment by p-janik** [comment]
Hey, I noticed recently that for example player returned by this lib doesn't contain app_id property. That was not the case before. 

It looks like for example updatePlayer expects player argument (error thrown in our case was `app_id must be a valid UUID`), so adding app_id to the player resource before update call fixes the issue.

Hopefully it helps someone here.

**Comment by thorep** [comment]
I also get 400 with no message of whats wrong.. if i remove external_id it works but i dont get an id in response..

  async sendNotification(sub: string, message: PushMessage): Promise<any> {
    const notification = new OneSignal.Notification();
    notification.app_id = process.env.ONESIGNAL_APPID;
    notification.name = message.name;
    notification.contents = message.contents;
    notification.headings = message.headings;
    notification.include_aliases = { alias_label: ['external_id'] };
    notification.external_id = sub;
    notification.target_channel = 'push';
    const notificationResponse =
      await this.client.createNotification(notification);
    console.log(notificationResponse);
    return notificationResponse;
  }

**Comment by JoeDareZone** [comment]
> Hey, I noticed recently that for example player returned by this lib doesn't contain app_id property. That was not the case before.
> 
> It looks like for example updatePlayer expects player argument (error thrown in our case was `app_id must be a valid UUID`), so adding app_id to the player resource before update call fixes the issue.
> 
> Hopefully it helps someone here.

You are my hero, I was stuck on this for ages
