### ISSUE TITLE
[Bug]: Missing app_id in Player object causes update failures

### ISSUE THREAD

**Issue by p-janik** [OneSignal/onesignal-node-api#78]
### What happened?

Recently, it was observed that players returned by the onesignal-node-api library do not contain the app_id property, which was previously included. This absence causes issues, particularly when attempting to update player information, as the operation expects a valid app_id, resulting in errors.

### Steps to reproduce?

To reproduce the issue, simply retrieve a player using the library and attempt to update the player's information without manually adding an app_id. The library will throw an error indicating that `app_id must be a valid UUID`.

### What did you expect to happen?

I expected the player object retrieved from the library to include the app_id property automatically, allowing for seamless updates without the need for manual intervention.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoeDareZone** [comment]
Thanks a million for this observation! Saved me hours of time.

**Comment by nan-li** [comment]
Thank you @p-janik for reporting and helping other users with your observation,

The node library makes the same server calls as someone hitting the OneSignal endpoints directly, passing the same information to and from the server.

It does look like the "get player" (https://documentation.onesignal.com/reference/view-device) endpoint is no longer returning `app_id` but the "update player" endpoint (https://documentation.onesignal.com/reference/edit-device) still requires it.

Apologies for the confusion.

**Comment by iAmWillShepherd** [comment]
It's my understanding that you have to provide an `App ID` to [View Device](https://documentation.onesignal.com/reference/view-device), so not having the property on each device shouldn't be an issue.
